version: "3.9"

services:
  redis:
    image: redis:7

  api:
    build:
      context: .
      dockerfile: Dockerfile
    command: [ "./api" ]
    ports:
      - "8080:8080"
    depends_on:
      - redis

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: [ "./worker" ]
    depends_on:
      - redis
