FROM golang:1.26-alpine

WORKDIR /app

# Install git + air
# RUN apk add --no-cache git
RUN go install github.com/air-verse/air@latest

# Cache deps
COPY go.mod go.sum ./
RUN go mod download

# Copy project
COPY . .

EXPOSE 8080

CMD ["air"]